Repository PNW-CS-Club/gkstudyhall, pull requests merged in 2024-02, with the labels that each got.

#1 Update README.md
  README.md
Labels: documentation

#3 Create GameManager Prefab
  GatekeeperStudyHall/.vsconfig
  GatekeeperStudyHall/Assets/Prefab.meta
  GatekeeperStudyHall/Assets/Prefab/GameManager.prefab
  GatekeeperStudyHall/Assets/Prefab/GameManager.prefab.meta
  GatekeeperStudyHall/Assets/Scenes/GkScene.unity
  GatekeeperStudyHall/Assets/Scenes/GkScene.unity.meta
Labels: enhancement, good first issue

#8 7 start menu
  GatekeeperStudyHall/Assets/Images.meta
  GatekeeperStudyHall/Assets/Images/gk_beach.png
  GatekeeperStudyHall/Assets/Images/gk_beach.png.meta
  GatekeeperStudyHall/Assets/Scenes/StartScene.unity
  GatekeeperStudyHall/Assets/Scenes/StartScene.unity.meta
  GatekeeperStudyHall/Assets/Scripts/StartMenuOnclick.cs
  GatekeeperStudyHall/Assets/Scripts/StartMenuOnclick.cs.meta
  GatekeeperStudyHall/Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Anton SDF.asset
  GatekeeperStudyHall/Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Bangers SDF.asset
  GatekeeperStudyHall/Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Electronic Highway Sign SDF.asset
  GatekeeperStudyHall/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#12 Fixed scene change bug
  GatekeeperStudyHall/ProjectSettings/EditorBuildSettings.asset
Labels: bug

#18 14 card data objects
  GatekeeperStudyHall/Assets/Cards.meta
  GatekeeperStudyHall/Assets/Cards/CardData.cs
  GatekeeperStudyHall/Assets/Cards/CardData.cs.meta
  GatekeeperStudyHall/Assets/Cards/CardDisplay.cs
  GatekeeperStudyHall/Assets/Cards/CardDisplay.cs.meta
  GatekeeperStudyHall/Assets/Cards/Sample Card.asset
  GatekeeperStudyHall/Assets/Cards/Sample Card.asset.meta
  GatekeeperStudyHall/Assets/Scenes/GkScene.unity
Labels: enhancement

#16 4-add board pdf
  GatekeeperStudyHall/Assets/Scenes/GkScene.unity
  GatekeeperStudyHall/Assets/Scenes/SampleScene.unity
  GatekeeperStudyHall/Assets/Scenes/SampleScene.unity.meta
  GatekeeperStudyHall/Assets/hype_board.png
  GatekeeperStudyHall/Assets/hype_board.png.meta
Labels: enhancement
